#pragma once
#define WIDTH 1200
#define HEIGHT 720

#define RADIUS 2
#define INITIAL_PARTICLES 5000
#define INITIAL_MASS 1e10f
#define HIGHEST_MASS (INITIAL_MASS * 3) // 

#define QUAD_TREE_DEPTH 50
#define QUAD_TREE_CAPACITY 1
#define QUAD_TREE_THETA 0.5f
