#pragma once
#define WIDTH 1200
#define HEIGHT 720

#define RADIUS 2
#define INITIAL_PARTICLES 2000
#define INITIAL_MASS 1.f
#define CIRCLE_TEXTURE_SIZE 1024

#define QUAD_TREE_MAX_DEPTH 128
#define QUAD_TREE_MAX_CAPACITY 1
#define QUAD_TREE_THETA 0.5f
